target 'HelloMSDKUI' do
    platform :ios, '10.0'
    # Use pod 'HEREMapsUI', '2.0' once the public podspec is available.
    # Until then you can point to the local podspec contained in this repo at the
    # following path, relative to this example app:
    pod 'HEREMapsUI', :path => '../../../'
end
