target 'HelloUIKit' do
    platform :ios, '10.0'
    pod 'HEREMaps', '3.8'
    pod 'MSDKUI', :path => '../../../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "MSDKUI"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end